apiVersion: v1
kind: Service
metadata:
  name: playback-service
  labels:
    app: playback-service
spec:
  selector:
    app: playback-service
  ports:
  - name: http
    port: 80
    targetPort: 8090
    protocol: TCP
  type: ClusterIP
  sessionAffinity: ClientIP  # Routes same client to same pod for cache locality
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 300  # 5 minutes
